title: Bimmer Gestalt
description: Exploring the symbiosis of phone and vehicle, together forming a greater whole than the sum of the parts.
github:
  is_project_page: false

remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - vendor
